# Generated by Django 4.1.4 on 2022-12-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='contact_number',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='contact_number_wa',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
