# Generated by Django 4.1.4 on 2022-12-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_settings_contact_number_settings_contact_number_wa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name_plural': 'settings'},
        ),
        migrations.AlterField(
            model_name='service',
            name='thumbnails',
            field=models.ManyToManyField(blank=True, to='service.thumbnail'),
        ),
    ]
