# Generated by Django 4.1.4 on 2022-12-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_settings_options_alter_service_thumbnails'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='excerpt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
