# Generated by Django 4.1.4 on 2022-12-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_service_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
