# Generated by Django 4.1.4 on 2023-01-04 16:28

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_settings_address_settings_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackrequest',
            options={'verbose_name': 'Geri Dönüş Talebi', 'verbose_name_plural': 'Geri Dönüş Talepleri'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Hizmet', 'verbose_name_plural': 'Hizmetler'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Ayar', 'verbose_name_plural': 'Ayarlar'},
        ),
        migrations.AlterModelOptions(
            name='thumbnail',
            options={'verbose_name': 'Hizmet Görüntüsü', 'verbose_name_plural': 'Hizmet Görüntüleri'},
        ),
        migrations.AddField(
            model_name='settings',
            name='contact_number_str',
            field=models.TextField(blank=True, verbose_name='Telefon Numarası (Görsel İçerik)'),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Mesajınız'),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-posta *'),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='name',
            field=models.CharField(max_length=255, verbose_name='İsim Soyisim *'),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Websiteniz'),
        ),
        migrations.AlterField(
            model_name='service',
            name='content',
            field=models.TextField(verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='service',
            name='excerpt',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa İçerik'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='service',
            name='thumbnails',
            field=models.ManyToManyField(blank=True, to='service.thumbnail', verbose_name='Görüntüler'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='contact_number',
            field=models.TextField(blank=True, verbose_name="Telefon Numarası (0'dan başlayan)"),
        ),
        migrations.AlterField(
            model_name='settings',
            name='contact_number_wa',
            field=models.TextField(blank=True, verbose_name="Telefon Numarası (Whatsapp 0'dan başlayan)"),
        ),
        migrations.AlterField(
            model_name='settings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Kurumsal Eposta'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='image',
            field=models.ImageField(upload_to='service/thumbnails/', verbose_name='Görüntü'),
        ),
    ]
